export const CONTACTUS_MAIL_REQUEST = "CONTACTUS_MAIL_REQUEST";
export const CONTACTUS_MAIL_SUCCESS = "CONTACTUS_MAIL_SUCCESS";
export const CONTACTUS_MAIL_FAIL = "CONTACTUS_MAIL_FAIL";
export const CONTACTUS_MAIL_RESET = "CONTACTUS_MAIL_RESET";

export const CLEAR_ERROR = "CLEAR_ERROR";
