export const CHANGE_WEBSITE_DETAILS_REQUEST = "CHANGE_WEBSITE_DETAILS_REQUEST";
export const CHANGE_WEBSITE_DETAILS_SUCCESS = "CHANGE_WEBSITE_DETAILS_SUCCESS";
export const CHANGE_WEBSITE_DETAILS_FAIL = "CHANGE_WEBSITE_DETAILS_FAIL";
export const CHANGE_WEBSITE_DETAILS_RESET = "CHANGE_WEBSITE_DETAILS_RESET";

export const WEBSITE_DETAILS_REQUEST = "WEBSITE_DETAILS_REQUEST";
export const WEBSITE_DETAILS_SUCCESS = "WEBSITE_DETAILS_SUCCESS";
export const WEBSITE_DETAILS_FAIL = "WEBSITE_DETAILS_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";
